language: node_js
node_js:
  - 14
  - lts/*
  - node
os:
  - windows
  - linux
  - osx
cache:
  directories:
    - node_modules
script:
  - npm run test:unit
# safelist
branches:
  only:
  - travis-test